pullrequest/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required
from django.urls import path
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from rest_framework.schemas import get_schema_view

from django.views.generic.base import TemplateView
from django.views.generic.edit import FormView
from django.views.generic.edit import CreateView


import pullapp.views.front_views as front_views
import pullapp.views.rest_views as rest_views

from pullapp.forms import SubmissionForm
from pullapp.forms import ConsumableForm

urlpatterns = [
    url(r'^$',
        login_required(
            TemplateView.as_view(template_name='pullapp/home.html')),
        name='home'),
    path('admin/', admin.site.urls),
    path('docs/',
         TemplateView.as_view(template_name='swagger-ui.html',
                              extra_context={'schema_url': 'openapi-schema'}),
         name='swagger-ui'),
    path('openapi/',
         get_schema_view(title="Your Project",
                         description="API for all things …",
                         version="1.0.0"),
         name='openapi-schema'),
    url(r'^submission/list/$', rest_views.SubmissionListGenericAPI.as_view()),
    url(r'^submission/create/$', rest_views.SubmissionCreateGenericAPI.as_view()),
    url(r'^submission/(?P<id_submission>[\w\-]+)/$', rest_views.SubmissionGenericAPI.as_view()),
    url(r'^submission/user/(?P<user_id>[\w\-]+)/list/$', rest_views.UserSubmissionListGenericAPI.as_view()),
    url(r'^consumable/list/$', rest_views.ConsumableListGenericAPI.as_view()),
    url(r'^consumable/create/$', rest_views.ConsumableCreateGenericAPI.as_view()),
    url(r'^consumable/(?P<id_material>[\w\-]+)/$', rest_views.ConsumableGenericAPI.as_view()),
    url(r'^printer/list/$', rest_views.PrinterListGenericAPI.as_view()),
    url(r'^printer/create/$', rest_views.PrinterCreateGenericAPI.as_view()),
    url(r'^printer/(?P<id_printer>[\w\-]+)/$', rest_views.PrinterGenericAPI.as_view()),
    url(r'^slice/(?P<id_submission>[\w\-]+)/$', rest_views.SlicerParamGenericAPI.as_view()),
    url(r'^signup/$', front_views.signup, name='signup'),
    url(r'^login/$', auth_views.LoginView.as_view(
        template_name='pullapp/login.html',
        redirect_authenticated_user=True), name='login'),
    url(r'^logout/$', auth_views.LogoutView.as_view(), name='logout'),
    url(r'^account/$',
        login_required(
            TemplateView.as_view(template_name='pullapp/account.html')),
        name='account'),
    url(r'^request/new/$',
        login_required(
            CreateView.as_view(
                template_name='pullapp/submission.html',
                form_class=SubmissionForm)),
        name='submission'),
    url(r'^material/new/$',
        login_required(
            CreateView.as_view(
                template_name='pullapp/material.html',
                form_class=ConsumableForm,
                success_url='/')),
        name='submission')
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

pullapp/models.py
import uuid

from django.core.validators import MinValueValidator
from django.contrib.auth import get_user_model
from django.contrib.postgres.fields import ArrayField
from django.db import models


class PrinterModel(models.Model):
    """
    Certains paramètres sont en relation avec les paramètres de l'imprimante
    L'imprimante doit donc avoir une entrée en base, définie selon le modèle:
    id_printer (UUIDField)
    name (CharField, 255)
    brand_model (Charfiel, 255)
    Layer_precision (Array Field, Integer) -- Précision d'une couche en microns
    Hotend_size (Array Field, Float) -- Diamètre de buses disponibles
    x_size (Integer) -- Taille X du plateau d'impression en mm
    y_size (Integer) -- Taille Y du plateau d'impression en mm
    z_size (Integer) -- Taille Z du plateau d'impression en mm
    dual_extruder (Boolean) -- Dispose de deux têtes d'impression
    heated_bed (Boolean) -- Dispose d'un plateau chauffant
    """
    id_printer = models.UUIDField(primary_key=True, default=uuid.uuid4)
    name = models.CharField(max_length=255)
    brand_model = models.CharField(max_length=255)
    layer_precision = ArrayField(
        models.FloatField(), blank=False, default=list([0.2]))
    hotend_size = ArrayField(
        models.FloatField(), blank=False, default=list([0.4]))
    x_size = models.IntegerField(
        blank=False, validators=[MinValueValidator(1)])
    y_size = models.IntegerField(
        blank=False, validators=[MinValueValidator(1)])
    z_size = models.IntegerField(
        blank=False, validators=[MinValueValidator(1)])
    dual_extruder = models.BooleanField(default=False)
    heated_bed = models.BooleanField(default=False)


class ConsumableModel(models.Model):
    """
    Chaque consommable est aussi renseigné en base
    id_material (UUIDField)
    consumable (CharField, 32) -- Type de consommable (PLA, ABS, ...)
    variant (Charfield, 255) -- Couleur, Spécial, ...
    diameter (Float) -- Diamètre du filament
    available (Boolean) -- En stock ou non
    """
    id_material = models.UUIDField(primary_key=True, default=uuid.uuid4)
    consumable = models.CharField(max_length=32, blank=False)
    variant = models.CharField(max_length=255, blank=False)
    diameter = models.FloatField(blank=False)
    available = models.BooleanField(default=True)

    def __str__(self):
        return f"{self.consumable} - {self.variant} - {self.diameter}mm"


DEFAULT_STATUS = 'SOUMIS'
STATUS_IMPRESSION = (
    ('SOUMIS', 'Soumis'),
    ('VALIDE', 'Validé'),
    ('EN ATTENTE', 'En attente'),
    ('REFUSE', 'Refusé'),
    ('IMPRESSION', 'Impression'),
    ('IMPRIME', 'Imprimé')
)


class SubmissionModel(models.Model):
    """
    Chaque soumission doit être enregistrée en base
    Une soumission devrait présenter les champs suivant:
    id_submission (UUIDField)
    designation (CharField, 255)  -- Désignation de l'objet
    about (TextField) - Description de l'impression, raison ...
    stl (BinaryField / FileField ?) -- Fichier Stl
    material (relation) -- Consommable d'impression
    copies (Integer) -- Nombre de même objet à imprimer (0 à 99+)
    submission_date (timestamp)
    update_date (timestamp)
    status (Enum) -- Status du process: Soumis, Accepté, Refusé, En attente, ..
    """
    id_submission = models.UUIDField(primary_key=True, default=uuid.uuid4)
    designation = models.CharField(max_length=255, blank=False)
    about = models.TextField(blank=True)
    stl = models.FileField(blank=False)
    material = models.ForeignKey(
        ConsumableModel, on_delete=models.SET_NULL, null=True)
    copies = models.IntegerField(default=0)
    submission_date = models.DateField(auto_now_add=True)
    submitted_by = models.ForeignKey(
        get_user_model(), on_delete=models.CASCADE)
    update_date = models.DateField(auto_now=True)
    status = models.CharField(
        max_length=10, choices=STATUS_IMPRESSION, default=DEFAULT_STATUS)
    # TODO: add user id


class SlicerParamsModel(models.Model):
    """
    This is generated by admin while treating a print request
    Those parameters are used into the final slicing
    printer (relation) -- Imprimante choisie pour l'impression
    hotend_diameter (Float) -- diamètre de la buse d'impression
    layer_resolution (Integer) -- Hauteur de couche standard
    support (Boolean) -- Nécessite des supports d'impression
    """
    id_params = models.UUIDField(primary_key=True, default=uuid.uuid4)
    submission = models.ForeignKey(
        SubmissionModel, on_delete=models.CASCADE, blank=False)
    printer = models.ForeignKey(
        PrinterModel, on_delete=models.SET_NULL, null=True)
    hotend_diameter = models.FloatField()
    layer_resolution = models.IntegerField()
    support = models.BooleanField(default=False)

pullapp/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.forms import ModelForm

from pullapp.models import SubmissionModel
from pullapp.models import ConsumableModel


class UserSignupForm(UserCreationForm):
    first_name = forms.CharField(
        max_length=30, required=False, help_text='Optional')
    last_name = forms.CharField(
        max_length=30, required=False, help_text='Optional')
    email = forms.EmailField(max_length=254, help_text='Required')

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1',
                  'password2')


class SubmissionForm(ModelForm):
    class Meta:
        model = SubmissionModel
        exclude = ['id_submission', 'status', ]


class ConsumableForm(ModelForm):
    class Meta:
        model = ConsumableModel
        exclude = ['id_material', 'available']

pullapp/views/front_views.py
from django.contrib.auth import login, authenticate
# from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render, redirect

from pullapp.forms import UserSignupForm


def signup(request):
    if request.method == 'POST':
        form = UserSignupForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('home')
    else:
        form = UserSignupForm()
    return render(request, 'pullapp/signup.html', {'form': form})

pullapp/views/rest_views.py
from django.shortcuts import render

from rest_framework import mixins, generics

from pullapp.serializers import SubmissionSerializer
from pullapp.serializers import SubmissionCreateOnlySerializer
from pullapp.serializers import SubmissionListAllSerializer
from pullapp.serializers import ConsumableSerializer
from pullapp.serializers import ConsumableCreateOnlySerializer
from pullapp.serializers import ConsumableListAllSerializer
from pullapp.serializers import PrinterSerializer
from pullapp.serializers import PrinterListAllSerializer
from pullapp.serializers import SlicerParamsSerializer
from pullapp.serializers import SlicerParamsListAllSerializer
from pullapp.models import SubmissionModel
from pullapp.models import ConsumableModel
from pullapp.models import PrinterModel
from pullapp.models import SlicerParamsModel


class SubmissionListGenericAPI(mixins.ListModelMixin,
                               generics.GenericAPIView):
    serializer_class = SubmissionListAllSerializer
    queryset = SubmissionModel.objects.all()

    def get(self, request, *args, **kwargs):
        """
        Get the list of all submissions
        """
        return self.list(request, *args, **kwargs)


class SubmissionCreateGenericAPI(mixins.CreateModelMixin,
                                 generics.GenericAPIView):
    serializer_class = SubmissionCreateOnlySerializer
    queryset = SubmissionModel.objects.all()

    def post(self, request, *args, **kwargs):
        """
        Create a submission
        """
        return self.create(request, *args, **kwargs)


class SubmissionGenericAPI(mixins.RetrieveModelMixin,
                           mixins.UpdateModelMixin,
                           mixins.DestroyModelMixin,
                           generics.GenericAPIView):
    serializer_class = SubmissionSerializer
    lookup_field = 'id_submission'
    queryset = SubmissionModel.objects.all()

    def get(self, request, *args, **kwargs):
        """
        Retreive a submission
        """
        return self.retrieve(request, *args, **kwargs)

    def patch(self, request, *args, **kwargs):
        """
        Update a submission
        """
        return self.partial_update(request, *args, **kwargs)

    def delete(self, request, *args, **kargs):
        """
        Delete a submission
        """
        return self.destroy(request, *args, **kwargs)


class UserSubmissionListGenericAPI(mixins.ListModelMixin,
                                   generics.GenericAPIView):
    serializer_class = SubmissionSerializer
    queryset = SubmissionModel.objects.all()  # NO

    # TODO: add get_queryset for user=user

    def get(self, request, *args, **kwargs):
        """
        List all submission from a user
        """
        return self.list(request, *args, **kwargs)


class ConsumableGenericAPI(mixins.RetrieveModelMixin,
                           mixins.UpdateModelMixin,
                           mixins.DestroyModelMixin,
                           generics.GenericAPIView):
    serializer_class = ConsumableSerializer
    lookup_field = 'id_material'
    queryset = ConsumableModel.objects.all()

    def get(self, request, *args, **kwargs):
        """
        Retreive a consumable
        """
        return self.retrieve(request, *args, **kwargs)

    def patch(self, request, *args, **kwargs):
        """
        Update is a consumable is avaialble or not
        other fields should be read-only
        """
        # TODO
        return self.partial_update(request, *args, **kwargs)

    def delete(self, request, *args, **kargs):
        """
        Delete a consumable
        """
        return self.destroy(request, *args, **kwargs)


class ConsumableCreateGenericAPI(mixins.CreateModelMixin,
                                 generics.GenericAPIView):
    serializer_class = ConsumableCreateOnlySerializer
    queryset = ConsumableModel.objects.all()

    def post(self, request, *args, **kwargs):
        """
        Create a consumable
        """
        return self.create(request, *args, **kwargs)


class ConsumableListGenericAPI(mixins.ListModelMixin,
                               generics.GenericAPIView):
    serializer_class = ConsumableListAllSerializer
    queryset = ConsumableModel.objects.all()

    def get(self, request, *args, **kwargs):
        """
        List all the consumables
        """
        return self.list(request, *args, **kwargs)


class PrinterGenericAPI(mixins.RetrieveModelMixin,
                        mixins.UpdateModelMixin,
                        mixins.DestroyModelMixin,
                        generics.GenericAPIView):
    serializer_class = PrinterSerializer
    lookup_field = 'id_printer'
    queryset = PrinterModel.objects.all()

    def get(self, request, *args, **kwargs):
        """
        Retreive a printer
        """
        return self.retrieve(request, *args, **kwargs)

    def patch(self, request, *args, **kwargs):
        """
        Update is a printer feature
        """
        # TODO
        return self.partial_update(request, *args, **kwargs)

    def delete(self, request, *args, **kwargs):
        """
        Delete a printer
        """
        return self.destroy(request, *args, **kwargs)


class PrinterCreateGenericAPI(mixins.CreateModelMixin,
                              generics.GenericAPIView):
    serializer_class = PrinterSerializer
    queryset = PrinterModel.objects.all()

    def post(self, request, *args, **kwargs):
        """
        Create a printer
        """
        return self.create(request, *args, **kwargs)


class PrinterListGenericAPI(mixins.ListModelMixin,
                            generics.GenericAPIView):
    serializer_class = PrinterListAllSerializer
    queryset = PrinterModel.objects.all()

    def get(self, request, *args, **kwargs):
        """
        List all the printers
        """
        return self.list(request, *args, **kwargs)


class SlicerParamGenericAPI(mixins.CreateModelMixin,
                            mixins.UpdateModelMixin,
                            mixins.DestroyModelMixin,
                            generics.GenericAPIView):
    serializer_class = SlicerParamsSerializer
    queryset = SlicerParamsModel.objects.all()

    def get(self, request, *args, **kwargs):
        """
        Retrieve the current slicing params of a submission
        """
        return self.retrieve(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        """
        Create slicing params for a submission
        Only one per submission can exist
        Return an error if there are existing params
        """
        return self.create(request, *args, **kwargs)

    def patch(self, request, *args, **kwargs):
        """
        Update the slicing params of a submission
        """
        return self.partial_update(request, *args, **kwargs)

pullapp/templates/pullapp/account.html
{% extends "pullapp/base.html" %}
{% block title %}My account{% endblock %}
{% block content %}

<h2>My account informations</h2>
<p>Username: {{ user.username }}</p>
<p>Real name: {{ user.get_full_name }}</p>
<p>Email: {{ user.email }}</p>
<p>Access: {{ user.groups.all.0 }}</p>
<p>Logged in since: {{ user.last_login }}</p>

{% endblock %}

pullapp/templates/pullapp/base.html
{% extends "pullapp/base_wo_navbar.html" %}
{% block navbar %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">Print Request</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav w-100">
        <li class="nav-item active">
            <a class="nav-link" href="/">Home</a>
        </li>
        {% if perms.pullapp.add_submissionmodel %}
        <li class="nav-item">
            <a class="nav-link" href="/request/new/">Create a request</a>
        </li>
        {% endif %}
        {% if perms.pullapp.add_slicerparamsmodel %}
        <li class="nav-item">
            <a class="nav-link" href="#">Manage requests</a>
        </li>
        {% endif %}
        {% if perms.pullapp.add_consumablemodel %}
        <li class="nav-item">
            <a class="nav-link" href="/material/new/">Add a material</a>
        </li>
        {% endif %}
        <li class="nav-item dropdown ml-auto">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Hello, {{ user.username }}
            </a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
            <a class="dropdown-item" href="/account/">My account</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="/logout/">Logout</a>
            </div>
        </li>
        </ul>
    </div>
</nav>
{% endblock %}

pullapp/templates/pullapp/base_wo_navbar.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <title>{% block title %}Print Request{% endblock %}</title>
</head>
<body>
    {% block navbar %}{% endblock %}
    <div id="content">
        {% block content %}{% endblock %}
    </div>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

pullapp/templates/pullapp/home.html
{% extends 'pullapp/base.html' %}
{% block title %}Home{% endblock %}
{% block content %}

<div class="container">
    <div class=row>
        <div class="col-lg-2">
            Menu nav
        </div>
        <div class="col">
            Content
        </div>
    </div>
</div>

{% endblock %}

pullapp/templates/pullapp/login.html
{% extends "pullapp/base_wo_navbar.html" %}
{% block title %}Login{% endblock %}
{% block content %}
<h2>Login</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Login</button>
</form>
<p>Doesn't have an account ? <a href="/signup/">Sign up here</a></p>
{% endblock %}

pullapp/templates/pullapp/material.html
{% extends "pullapp/submit_new_form.html" %}
{% block submit_type %}material{% endblock %}
{% block action %}/consumable/create/{% endblock %}

pullapp/templates/pullapp/signup.html
{% extends "pullapp/base_wo_navbar.html" %}

{% block title %}Sign Up{% endblock %}
{% block content %}
<h2>Sign up</h2>
<form method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <button type="submit">Submit</button>
</form>
{% endblock %}

pullapp/templates/pullapp/submission.html
{% extends "pullapp/submit_new_form.html" %}
{% block submit_type %}request{% endblock %}

pullapp/templates/pullapp/submit_new_form.html
{% extends "pullapp/base.html" %}
{% block title %}New request{% endblock %}
{% block content %}

<h2>Create a new {% block submit_type %}{% endblock %}</h2>
<form  method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
</table>
    <button type="submit">Submit</button>
</form>

{% endblock %}